name: gstu_cse
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.1
  get_storage: ^2.1.1
  file_picker: ^10.3.7
  url_launcher: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

